#ifndef PROFILE_GMR_H
#define PROFILE_GMR_H

/* GMR产品默认功能组合；命令行-D仍可覆盖单个METHOD用于构建验证。 */
#ifndef CAR_LIBRARY_GRAY_INPUT_METHOD
#define CAR_LIBRARY_GRAY_INPUT_METHOD \
    CAR_LIBRARY_GRAY_INPUT_DIGITAL_GPIO_7
#endif
#ifndef CAR_LIBRARY_LINE_FOLLOW_METHOD
#define CAR_LIBRARY_LINE_FOLLOW_METHOD \
    CAR_LIBRARY_LINE_FOLLOW_NONE
#endif
#ifndef CAR_LIBRARY_LINE_DRIVE_METHOD
#define CAR_LIBRARY_LINE_DRIVE_METHOD \
    CAR_LIBRARY_LINE_DRIVE_ENCODER_SPEED_LOOP
#endif
#ifndef CAR_LIBRARY_RIGHT_ANGLE_TURN_METHOD
#define CAR_LIBRARY_RIGHT_ANGLE_TURN_METHOD \
    CAR_LIBRARY_RIGHT_ANGLE_TURN_NONE
#endif
#ifndef CAR_LIBRARY_TURN_SPEED_METHOD
#define CAR_LIBRARY_TURN_SPEED_METHOD \
    CAR_LIBRARY_TURN_SPEED_FIXED
#endif
#ifndef CAR_LIBRARY_GIMBAL_TRACKING_METHOD
#define CAR_LIBRARY_GIMBAL_TRACKING_METHOD \
    CAR_LIBRARY_GIMBAL_TRACKING_NONE
#endif
#ifndef CAR_LIBRARY_GIMBAL_ATTITUDE_METHOD
#define CAR_LIBRARY_GIMBAL_ATTITUDE_METHOD \
    CAR_LIBRARY_GIMBAL_ATTITUDE_NONE
#endif
#ifndef CAR_LIBRARY_GIMBAL_STARTUP_SEARCH_METHOD
#define CAR_LIBRARY_GIMBAL_STARTUP_SEARCH_METHOD \
    CAR_LIBRARY_GIMBAL_STARTUP_SEARCH_NONE
#endif
#ifndef CAR_LIBRARY_GIMBAL_LOST_TARGET_METHOD
#define CAR_LIBRARY_GIMBAL_LOST_TARGET_METHOD \
    CAR_LIBRARY_GIMBAL_LOST_TARGET_NONE
#endif
#ifndef CAR_LIBRARY_GIMBAL_TURN_FOLLOW_METHOD
#define CAR_LIBRARY_GIMBAL_TURN_FOLLOW_METHOD \
    CAR_LIBRARY_GIMBAL_TURN_FOLLOW_NONE
#endif
#ifndef CAR_LIBRARY_H7_LCD_METHOD
#define CAR_LIBRARY_H7_LCD_METHOD \
    CAR_LIBRARY_H7_LCD_UART_TEXT
#endif
#ifndef CAR_LIBRARY_H7_IMU_METHOD
#if defined(GMR_H7_IMU_ENABLED) && GMR_H7_IMU_ENABLED
#define CAR_LIBRARY_H7_IMU_METHOD \
    CAR_LIBRARY_H7_IMU_UART_JY61
#else
#define CAR_LIBRARY_H7_IMU_METHOD \
    CAR_LIBRARY_H7_IMU_NONE
#endif
#endif
#ifndef CAR_LIBRARY_IMU660RX_METHOD
#define CAR_LIBRARY_IMU660RX_METHOD \
    CAR_LIBRARY_IMU660RX_NONE
#endif
#ifndef CAR_LIBRARY_LOCAL_OLED_METHOD
#define CAR_LIBRARY_LOCAL_OLED_METHOD \
    CAR_LIBRARY_LOCAL_OLED_I2C_SSD1306
#endif
#endif
