#ifndef BLUETOOTH_CONFIG_H
#define BLUETOOTH_CONFIG_H

#define CAR_BLUETOOTH_ROLE_DISABLED      (0U)
#define CAR_BLUETOOTH_ROLE_MASTER        (1U)
#define CAR_BLUETOOTH_ROLE_SLAVE         (2U)

/* Normal project builds target the Dimeng car's HC-05 slave module. */
#ifndef CAR_BLUETOOTH_ROLE
#define CAR_BLUETOOTH_ROLE               CAR_BLUETOOTH_ROLE_SLAVE
#endif

#if ((CAR_BLUETOOTH_ROLE != CAR_BLUETOOTH_ROLE_DISABLED) && \
    (CAR_BLUETOOTH_ROLE != CAR_BLUETOOTH_ROLE_MASTER) && \
    (CAR_BLUETOOTH_ROLE != CAR_BLUETOOTH_ROLE_SLAVE))
#error "CAR_BLUETOOTH_ROLE must be Disabled, Master, or Slave"
#endif

#define CAR_BLUETOOTH_ENABLED \
    (CAR_BLUETOOTH_ROLE != CAR_BLUETOOTH_ROLE_DISABLED)

#define CAR_BLUETOOTH_MASTER_NODE_ID     (1U)
#define CAR_BLUETOOTH_SLAVE_NODE_ID      (2U)

#define CAR_BLUETOOTH_MASTER_MAC_TEXT    "002506010DD3"
#define CAR_BLUETOOTH_SLAVE_MAC_TEXT     "98DA50030177"
#define CAR_BLUETOOTH_SLAVE_BIND_TEXT    "98da,50,030177"

#define CAR_BLUETOOTH_MASTER_MAC_BYTES \
    0x00U, 0x25U, 0x06U, 0x01U, 0x0DU, 0xD3U
#define CAR_BLUETOOTH_SLAVE_MAC_BYTES \
    0x98U, 0xDAU, 0x50U, 0x03U, 0x01U, 0x77U

#define CAR_BLUETOOTH_AT_BAUD_RATE       (38400U)
#define CAR_BLUETOOTH_DATA_BAUD_RATE     (115200U)
#define CAR_BLUETOOTH_HELLO_PERIOD_MS    (1000U)
#define CAR_BLUETOOTH_LINK_TIMEOUT_MS    (3500U)

/* The board profile selects UART2 on Tianmeng or UART3 on Dimeng. */
#define CAR_BLUETOOTH_TRANSPORT_CONFIGURED (1U)

#if (CAR_BLUETOOTH_ROLE == CAR_BLUETOOTH_ROLE_MASTER)
#define CAR_BLUETOOTH_LOCAL_NODE_ID      CAR_BLUETOOTH_MASTER_NODE_ID
#define CAR_BLUETOOTH_PEER_NODE_ID       CAR_BLUETOOTH_SLAVE_NODE_ID
#define CAR_BLUETOOTH_PEER_ROLE          CAR_BLUETOOTH_ROLE_SLAVE
#define CAR_BLUETOOTH_LOCAL_MAC_TEXT     CAR_BLUETOOTH_MASTER_MAC_TEXT
#define CAR_BLUETOOTH_PEER_MAC_TEXT      CAR_BLUETOOTH_SLAVE_MAC_TEXT
#define CAR_BLUETOOTH_LOCAL_MAC_BYTES    CAR_BLUETOOTH_MASTER_MAC_BYTES
#define CAR_BLUETOOTH_PEER_MAC_BYTES     CAR_BLUETOOTH_SLAVE_MAC_BYTES
#define CAR_BLUETOOTH_ROLE_NAME          "Master"
#elif (CAR_BLUETOOTH_ROLE == CAR_BLUETOOTH_ROLE_SLAVE)
#define CAR_BLUETOOTH_LOCAL_NODE_ID      CAR_BLUETOOTH_SLAVE_NODE_ID
#define CAR_BLUETOOTH_PEER_NODE_ID       CAR_BLUETOOTH_MASTER_NODE_ID
#define CAR_BLUETOOTH_PEER_ROLE          CAR_BLUETOOTH_ROLE_MASTER
#define CAR_BLUETOOTH_LOCAL_MAC_TEXT     CAR_BLUETOOTH_SLAVE_MAC_TEXT
#define CAR_BLUETOOTH_PEER_MAC_TEXT      CAR_BLUETOOTH_MASTER_MAC_TEXT
#define CAR_BLUETOOTH_LOCAL_MAC_BYTES    CAR_BLUETOOTH_SLAVE_MAC_BYTES
#define CAR_BLUETOOTH_PEER_MAC_BYTES     CAR_BLUETOOTH_MASTER_MAC_BYTES
#define CAR_BLUETOOTH_ROLE_NAME          "Slave"
#else
#define CAR_BLUETOOTH_LOCAL_NODE_ID      (0U)
#define CAR_BLUETOOTH_PEER_NODE_ID       (0U)
#define CAR_BLUETOOTH_PEER_ROLE          CAR_BLUETOOTH_ROLE_DISABLED
#define CAR_BLUETOOTH_LOCAL_MAC_TEXT     "000000000000"
#define CAR_BLUETOOTH_PEER_MAC_TEXT      "000000000000"
#define CAR_BLUETOOTH_LOCAL_MAC_BYTES    0U, 0U, 0U, 0U, 0U, 0U
#define CAR_BLUETOOTH_PEER_MAC_BYTES     0U, 0U, 0U, 0U, 0U, 0U
#define CAR_BLUETOOTH_ROLE_NAME          "Disabled"
#endif

#endif
