#ifndef PIN_MAP_H
#define PIN_MAP_H

#include "ti_msp_dl_config.h"

/*
 * Pin source: 地猛星最小系统板 H3/H5 引脚排布 + ccs1.2 接线表。
 * 详细约束见 doc/PIN_ASSIGNMENT_2026-05-23.md。
 */

/*
 * 四个闭环步进驱动器使用 DIR/STEP 控制。
 * 这些宏只描述 MCU 到驱动器控制口的逻辑线，电机相线和驱动电源不接 MCU。
 */
#define PIN_STEPPER_CHASSIS_LEFT_STEP_PORT   STEPPER_CHASSIS_LEFT_STEP_PORT
#define PIN_STEPPER_CHASSIS_LEFT_STEP        STEPPER_CHASSIS_LEFT_STEP_PIN
#define PIN_STEPPER_CHASSIS_LEFT_DIR_PORT    STEPPER_CHASSIS_LEFT_DIR_PORT
#define PIN_STEPPER_CHASSIS_LEFT_DIR         STEPPER_CHASSIS_LEFT_DIR_PIN

#define PIN_STEPPER_CHASSIS_RIGHT_STEP_PORT  STEPPER_CHASSIS_RIGHT_STEP_PORT
#define PIN_STEPPER_CHASSIS_RIGHT_STEP       STEPPER_CHASSIS_RIGHT_STEP_PIN
#define PIN_STEPPER_CHASSIS_RIGHT_DIR_PORT   STEPPER_CHASSIS_RIGHT_DIR_PORT
#define PIN_STEPPER_CHASSIS_RIGHT_DIR        STEPPER_CHASSIS_RIGHT_DIR_PIN

#define PIN_STEPPER_GIMBAL_1_STEP_PORT       STEPPER_GIMBAL_1_STEP_PORT
#define PIN_STEPPER_GIMBAL_1_STEP            STEPPER_GIMBAL_1_STEP_PIN
#define PIN_STEPPER_GIMBAL_1_DIR_PORT        STEPPER_GIMBAL_1_DIR_PORT
#define PIN_STEPPER_GIMBAL_1_DIR             STEPPER_GIMBAL_1_DIR_PIN

#define PIN_STEPPER_GIMBAL_2_STEP_PORT       STEPPER_GIMBAL_2_STEP_PORT
#define PIN_STEPPER_GIMBAL_2_STEP            STEPPER_GIMBAL_2_STEP_PIN
#define PIN_STEPPER_GIMBAL_2_DIR_PORT        STEPPER_GIMBAL_2_DIR_PORT
#define PIN_STEPPER_GIMBAL_2_DIR             STEPPER_GIMBAL_2_DIR_PIN

#define PIN_ENCODER_PORT                ENCODER_PORT
#define PIN_ENCODER_LEFT_A              ENCODER_LEFT_A_PIN
#define PIN_ENCODER_LEFT_B              ENCODER_LEFT_B_PIN
#define PIN_ENCODER_RIGHT_A             ENCODER_RIGHT_A_PIN
#define PIN_ENCODER_RIGHT_B             ENCODER_RIGHT_B_PIN

#define PIN_KEY_PORT                    KEY_PORT
#define PIN_KEY_1                       KEY_1_PIN
#define PIN_KEY_2                       KEY_2_PIN

#define PIN_GRAY_ADC0                   GRAY_ADC0_INST
#define PIN_GRAY_ADC1                   GRAY_ADC1_INST

#endif
